name: freevad_check CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup Node latest
      uses: actions/setup-node@v3
      with:
        node-version: 'node'
    - name: Install dependencies
      run: npm install
    - name: Run Jest with Coverage
      run: npm test -- --coverage
    - name: Download Code Climate Test Reporter
      run: |
        curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        chmod +x ./cc-test-reporter
    - name: Before build
      run: ./cc-test-reporter before-build
    - name: Upload coverage data to Code Climate
      run: |
        ./cc-test-reporter after-build --exit-code ${{ job.status }} --id ${{ secrets.code_c_tpid_fr }}
