name: freevad_check CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup Node latest
      uses: actions/setup-node@v3
      with:
        node-version: 'node'
    - name: Install dependencies
      run: npm install
    - name: Run Jest with Coverage
      run: npm test -- --coverage
    - name: Publish code coverage to code-climate (duh)
      uses: paambaati/codeclimate-action@v5.0.0
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CODE_C_TRID_FR }}
      with:
        debug: true
        coverageLocations: |
          ${{github.workspace}}/.tap/report/lcov.info:lcov
